import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  ReactNode,
} from 'react';

/** Supported languages. `flag` is a country flag emoji used by the switcher UI. */
export const LANGUAGES = [
  { code: 'en', label: 'English',  flag: '🇺🇸' },
  { code: 'es', label: 'Español',  flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch',  flag: '🇩🇪' },
  { code: 'zh', label: '中文',      flag: '🇨🇳' },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]['code'];

/**
 * Every translatable string in the app is keyed here.
 * Keys that are not translated for a given language fall back to English.
 */
type TranslationDict = Record<string, string>;

const EN: TranslationDict = {
  // Brand / chrome
  'brand.name': 'Northbound',

  // Sidebar
  'nav.dashboard': 'Dashboard',
  'nav.myOrders': 'My Orders',
  'nav.orders': 'Orders',
  'nav.receivedOrders': 'Received Orders',
  'nav.templates': 'Templates',
  'nav.analytics': 'Analytics',
  'nav.settings': 'Settings',
  'nav.buyerAccount': 'Buyer account',
  'nav.sellerAccount': 'Seller account',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle.buyer': 'Purchase order management for your business',
  'dashboard.subtitle.seller': 'Seller overview — track the orders coming in from your buyers',
  'dashboard.totalOrders': 'Total Orders',
  'dashboard.ordersReceived': 'Orders Received',
  'dashboard.totalSpend': 'Total Spend',
  'dashboard.totalRevenue': 'Total Revenue',
  'dashboard.pendingOrders': 'Pending Orders',
  'dashboard.ordersShipped': 'Orders Shipped',
  'dashboard.recurringTemplates': 'Recurring Templates',
  'dashboard.recentOrders': 'Recent Orders',
  'dashboard.recentReceivedOrders': 'Recent Received Orders',
  'dashboard.quickActions': 'Quick Actions',
  'dashboard.createOrder': 'Create Order',
  'dashboard.newTemplate': 'New Template',
  'dashboard.viewAllReceived': 'View All Received Orders',
  'dashboard.completeProfilePrompt': 'Complete your profile to unlock buyer/seller features.',
  'dashboard.setUpProfile': 'Set up profile',
  'dashboard.col.orderId': 'Order ID',
  'dashboard.col.currency': 'Currency',
  'dashboard.col.issueDate': 'Issue Date',
  'dashboard.col.type': 'Type',
  'dashboard.col.status': 'Status',
  'dashboard.loadingOrders': 'Loading orders…',
  'dashboard.noOrders': 'No orders found.',
  'dashboard.type.recurring': 'Recurring',
  'dashboard.type.oneOff': 'One-off',
  'dashboard.couldNotLoad': 'Could not load orders',

  // Settings
  'settings.title': 'Settings',
  'settings.subtitle': 'Account and platform preferences',
  'settings.account': 'Account',
  'settings.userId': 'User ID',
  'settings.email': 'Email',
  'settings.session': 'Session',
  'settings.sessionActive': 'Active',
  'settings.partyIdentity': 'Party Identity',
  'settings.partyIdentityDesc': 'Your party ID is automatically set to your email address and cannot be changed.',
  'settings.partyIdentityDescSellerSuffix': 'Share it with buyers so they can reference you when placing orders.',
  'settings.partyIdLabel': 'Party ID (external_id)',
  'settings.roleLabel': 'Role',
  'settings.role': 'Role',
  'settings.roleDesc': 'Your role determines what you can do in Northbound. Buyers create orders; sellers receive and fulfil them.',
  'settings.role.buyer': 'Buyer',
  'settings.role.seller': 'Seller',
  'settings.saveRole': 'Save Role',
  'settings.saved': 'Saved!',
  'settings.preferences': 'Preferences',
  'settings.preferencesDesc': 'These preferences are saved locally and used to pre-fill forms throughout the app.',
  'settings.defaultCurrency': 'Default Currency',
  'settings.savedInstantly': 'Saved instantly — no need to click Save.',
  'settings.platform': 'Platform',
  'settings.platform.application': 'Application',
  'settings.platform.purpose': 'Purpose',
  'settings.platform.purposeValue': 'Purchase order management for small and medium businesses',
  'settings.platform.docStandard': 'Document Standard',
  'settings.platform.backendUrl': 'Backend URL',
  'settings.language': 'Language',
  'settings.buyerProfile': 'Buyer Profile',
  'settings.buyerProfileDesc': 'Saved locally and used to pre-fill the buyer section when creating an order or template.',

  // Buyer profile fields (also reused on forms)
  'profile.orgName': 'Organisation Name',
  'profile.contactEmail': 'Contact Email',
  'profile.street': 'Street',
  'profile.city': 'City',
  'profile.country': 'Country',
  'profile.postalCode': 'Postal Code',
  'profile.orgNamePlaceholder': 'e.g. Acme Pty Ltd',
  'profile.contactEmailPlaceholder': 'contact@example.com',
  'profile.countryPlaceholder': 'e.g. AU',

  // Templates list
  'templates.title': 'Recurring Templates',
  'templates.subtitle': 'Manage repeat purchase orders',
  'templates.newTemplate': '+ New Template',
  'templates.loading': 'Loading templates…',
  'templates.empty': 'No recurring templates yet.',
  'templates.loadError': 'Could not load templates',
  'templates.col.name': 'Name',
  'templates.col.currency': 'Currency',
  'templates.col.frequency': 'Frequency',
  'templates.col.interval': 'Interval',
  'templates.col.startDate': 'Start Date',
  'templates.col.endDate': 'End Date',
  'templates.col.actions': 'Actions',
  'templates.edit': 'Edit',
  'templates.delete': 'Delete',
  'templates.ongoing': 'Ongoing',
  'templates.deleteConfirm': 'Delete this template?',
  'templates.deleteBodyPrefix': 'Template',
  'templates.deleteBodySuffix': 'will be permanently deleted. This cannot be undone.',
  'templates.deleting': 'Deleting…',

  // Create / Edit Template
  'createTemplate.backToTemplates': '← Back to Templates',
  'createTemplate.title': 'New Recurring Template',
  'createTemplate.templateName': 'Template Name',
  'createTemplate.nameLabel': 'Name',
  'createTemplate.namePlaceholder': 'e.g. Monthly office supplies',
  'createTemplate.nameHelp': 'Used to identify this template in lists and dropdowns.',
  'createTemplate.nameHelpEdit': 'Used to identify this template in lists and dropdowns. Leave blank to use a shortened ID.',
  'editTemplate.title': 'Edit Template',
  'editTemplate.loading': 'Loading template…',
  'editTemplate.notFound': 'Template not found.',
  'editTemplate.saving': 'Saving…',
  'editTemplate.saveChanges': 'Save Changes',
  'createTemplate.submit': 'Create Template',
  'createTemplate.submitting': 'Creating…',
  'createTemplate.recurrenceSettings': 'Recurrence Settings',
  'createTemplate.frequency': 'Frequency',
  'createTemplate.interval': 'Interval',
  'createTemplate.startDate': 'Start Date',
  'createTemplate.endDate': 'End Date',
  'createTemplate.endDateOptional': '(optional)',
  'createTemplate.currency': 'Currency',
  'createTemplate.note': 'Note',
  'createTemplate.notePlaceholder': 'Optional note',
  'createTemplate.orderLines': 'Order Lines',
  'createTemplate.addLine': '+ Add Line',
  'createTemplate.buyerSection': 'Buyer (Your Organisation)',
  'createTemplate.sellerSection': 'Seller (Supplier)',

  // Saved seller picker
  'savedSeller.heading': 'Load a Saved Supplier',
  'savedSeller.label': 'Saved Suppliers',
  'savedSeller.selectPlaceholder': '— Select a saved supplier —',
  'savedSeller.forget': 'Forget',
  'savedSeller.forgetTitle': 'Forget this supplier',
  'savedSeller.help': 'Selecting a supplier pre-fills the seller fields below. You can still edit them.',

  // Orders page
  'orders.title.buyer': 'My Orders',
  'orders.title.seller': 'Received Orders',
  'orders.subtitleFor': 'Showing orders for {role} ID: {id}',
  'orders.role.buyer': 'buyer',
  'orders.role.seller': 'seller',
  'orders.setupPrompt': 'Set up your profile in Settings to filter to your own orders',
  'orders.newOrder': '+ New Order',
  'orders.filter.all': 'All',
  'orders.filter.oneOff': 'One-off',
  'orders.filter.recurring': 'Recurring',
  'orders.col.note': 'Note',
  'orders.loadError': 'Could not load orders',
  'orders.status.pending': 'Pending',
  'orders.status.shipped': 'Shipped',
  'orders.status.delivered': 'Delivered',

  // Analytics page
  'analytics.title': 'Analytics',
  'analytics.subtitle.buyer': 'Summary of your purchasing activity',
  'analytics.subtitle.seller': 'Summary of orders received',
  'analytics.loading': 'Loading analytics…',
  'analytics.empty': 'No orders yet — analytics will appear here once you have orders.',
  'analytics.stat.totalOrders': 'Total Orders',
  'analytics.stat.oneOff': 'One-off',
  'analytics.stat.recurring': 'Recurring',
  'analytics.stat.pending': 'Pending',
  'analytics.stat.shipped': 'Shipped',
  'analytics.stat.delivered': 'Delivered',
  'analytics.byStatus': 'Orders by Status',
  'analytics.byCurrency': 'Orders by Currency',
  'analytics.recurringFrequency': 'Recurring Frequency',
  'analytics.recurringOfTotal': '{n} of {total} orders are recurring',
  'analytics.ordersPerMonth': 'Orders per Month',
  'analytics.recentOrders': 'Recent Orders',
  'analytics.col.date': 'Date',
  'analytics.freq.DAILY': 'Daily',
  'analytics.freq.WEEKLY': 'Weekly',
  'analytics.freq.MONTHLY': 'Monthly',

  // Common buttons / words
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.logout': 'Log Out',
};

const ES: TranslationDict = {
  'brand.name': 'Northbound',
  'nav.dashboard': 'Panel',
  'nav.myOrders': 'Mis Pedidos',
  'nav.orders': 'Pedidos',
  'nav.receivedOrders': 'Pedidos Recibidos',
  'nav.templates': 'Plantillas',
  'nav.analytics': 'Analítica',
  'nav.settings': 'Configuración',
  'nav.buyerAccount': 'Cuenta de comprador',
  'nav.sellerAccount': 'Cuenta de vendedor',

  'dashboard.title': 'Panel',
  'dashboard.subtitle.buyer': 'Gestión de órdenes de compra para tu negocio',
  'dashboard.subtitle.seller': 'Vista del vendedor — sigue los pedidos que llegan de tus compradores',
  'dashboard.totalOrders': 'Pedidos Totales',
  'dashboard.ordersReceived': 'Pedidos Recibidos',
  'dashboard.totalSpend': 'Gasto Total',
  'dashboard.totalRevenue': 'Ingresos Totales',
  'dashboard.pendingOrders': 'Pedidos Pendientes',
  'dashboard.ordersShipped': 'Pedidos Enviados',
  'dashboard.recurringTemplates': 'Plantillas Recurrentes',
  'dashboard.recentOrders': 'Pedidos Recientes',
  'dashboard.recentReceivedOrders': 'Pedidos Recibidos Recientes',
  'dashboard.quickActions': 'Acciones Rápidas',
  'dashboard.createOrder': 'Crear Pedido',
  'dashboard.newTemplate': 'Nueva Plantilla',
  'dashboard.viewAllReceived': 'Ver Todos los Pedidos Recibidos',
  'dashboard.completeProfilePrompt': 'Completa tu perfil para desbloquear funciones de comprador/vendedor.',
  'dashboard.setUpProfile': 'Configurar perfil',
  'dashboard.col.orderId': 'ID del Pedido',
  'dashboard.col.currency': 'Moneda',
  'dashboard.col.issueDate': 'Fecha de Emisión',
  'dashboard.col.type': 'Tipo',
  'dashboard.col.status': 'Estado',
  'dashboard.loadingOrders': 'Cargando pedidos…',
  'dashboard.noOrders': 'No se encontraron pedidos.',
  'dashboard.type.recurring': 'Recurrente',
  'dashboard.type.oneOff': 'Único',
  'dashboard.couldNotLoad': 'No se pudieron cargar los pedidos',

  'settings.title': 'Configuración',
  'settings.subtitle': 'Preferencias de cuenta y plataforma',
  'settings.account': 'Cuenta',
  'settings.userId': 'ID de Usuario',
  'settings.email': 'Correo electrónico',
  'settings.session': 'Sesión',
  'settings.sessionActive': 'Activa',
  'settings.partyIdentity': 'Identidad de la Parte',
  'settings.partyIdentityDesc': 'Tu ID de parte se establece automáticamente a tu dirección de correo y no se puede cambiar.',
  'settings.partyIdentityDescSellerSuffix': 'Compártela con compradores para que puedan referenciarte al realizar pedidos.',
  'settings.partyIdLabel': 'ID de Parte (external_id)',
  'settings.roleLabel': 'Rol',
  'settings.role': 'Rol',
  'settings.roleDesc': 'Tu rol determina qué puedes hacer en Northbound. Los compradores crean pedidos; los vendedores los reciben y los cumplen.',
  'settings.role.buyer': 'Comprador',
  'settings.role.seller': 'Vendedor',
  'settings.saveRole': 'Guardar Rol',
  'settings.saved': '¡Guardado!',
  'settings.preferences': 'Preferencias',
  'settings.preferencesDesc': 'Estas preferencias se guardan localmente y se usan para rellenar formularios en toda la aplicación.',
  'settings.defaultCurrency': 'Moneda Predeterminada',
  'settings.savedInstantly': 'Guardado al instante — no es necesario hacer clic en Guardar.',
  'settings.platform': 'Plataforma',
  'settings.platform.application': 'Aplicación',
  'settings.platform.purpose': 'Propósito',
  'settings.platform.purposeValue': 'Gestión de órdenes de compra para pequeñas y medianas empresas',
  'settings.platform.docStandard': 'Estándar de Documento',
  'settings.platform.backendUrl': 'URL del Backend',
  'settings.language': 'Idioma',
  'settings.buyerProfile': 'Perfil del Comprador',
  'settings.buyerProfileDesc': 'Guardado localmente y usado para rellenar la sección del comprador al crear un pedido o plantilla.',

  'profile.orgName': 'Nombre de la Organización',
  'profile.contactEmail': 'Correo de Contacto',
  'profile.street': 'Calle',
  'profile.city': 'Ciudad',
  'profile.country': 'País',
  'profile.postalCode': 'Código Postal',
  'profile.orgNamePlaceholder': 'p. ej. Acme Pty Ltd',
  'profile.contactEmailPlaceholder': 'contacto@ejemplo.com',
  'profile.countryPlaceholder': 'p. ej. AU',

  'templates.title': 'Plantillas Recurrentes',
  'templates.subtitle': 'Gestionar órdenes de compra recurrentes',
  'templates.newTemplate': '+ Nueva Plantilla',
  'templates.loading': 'Cargando plantillas…',
  'templates.empty': 'Aún no hay plantillas recurrentes.',
  'templates.loadError': 'No se pudieron cargar las plantillas',
  'templates.col.name': 'Nombre',
  'templates.col.currency': 'Moneda',
  'templates.col.frequency': 'Frecuencia',
  'templates.col.interval': 'Intervalo',
  'templates.col.startDate': 'Fecha de Inicio',
  'templates.col.endDate': 'Fecha de Fin',
  'templates.col.actions': 'Acciones',
  'templates.edit': 'Editar',
  'templates.delete': 'Eliminar',
  'templates.ongoing': 'En curso',
  'templates.deleteConfirm': '¿Eliminar esta plantilla?',
  'templates.deleteBodyPrefix': 'La plantilla',
  'templates.deleteBodySuffix': 'se eliminará permanentemente. Esto no se puede deshacer.',
  'templates.deleting': 'Eliminando…',

  'createTemplate.backToTemplates': '← Volver a Plantillas',
  'createTemplate.title': 'Nueva Plantilla Recurrente',
  'createTemplate.templateName': 'Nombre de la Plantilla',
  'createTemplate.nameLabel': 'Nombre',
  'createTemplate.namePlaceholder': 'p. ej. Suministros mensuales de oficina',
  'createTemplate.nameHelp': 'Se usa para identificar esta plantilla en listas y desplegables.',
  'createTemplate.nameHelpEdit': 'Se usa para identificar esta plantilla en listas y desplegables. Déjalo en blanco para usar un ID abreviado.',
  'editTemplate.title': 'Editar Plantilla',
  'editTemplate.loading': 'Cargando plantilla…',
  'editTemplate.notFound': 'Plantilla no encontrada.',
  'editTemplate.saving': 'Guardando…',
  'editTemplate.saveChanges': 'Guardar Cambios',
  'createTemplate.submit': 'Crear Plantilla',
  'createTemplate.submitting': 'Creando…',
  'createTemplate.recurrenceSettings': 'Ajustes de Recurrencia',
  'createTemplate.frequency': 'Frecuencia',
  'createTemplate.interval': 'Intervalo',
  'createTemplate.startDate': 'Fecha de Inicio',
  'createTemplate.endDate': 'Fecha de Fin',
  'createTemplate.endDateOptional': '(opcional)',
  'createTemplate.currency': 'Moneda',
  'createTemplate.note': 'Nota',
  'createTemplate.notePlaceholder': 'Nota opcional',
  'createTemplate.orderLines': 'Líneas del Pedido',
  'createTemplate.addLine': '+ Añadir Línea',
  'createTemplate.buyerSection': 'Comprador (Tu Organización)',
  'createTemplate.sellerSection': 'Vendedor (Proveedor)',

  'savedSeller.heading': 'Cargar un Proveedor Guardado',
  'savedSeller.label': 'Proveedores Guardados',
  'savedSeller.selectPlaceholder': '— Selecciona un proveedor guardado —',
  'savedSeller.forget': 'Olvidar',
  'savedSeller.forgetTitle': 'Olvidar este proveedor',
  'savedSeller.help': 'Seleccionar un proveedor rellena los campos del vendedor a continuación. Aún puedes editarlos.',

  'orders.title.buyer': 'Mis Pedidos',
  'orders.title.seller': 'Pedidos Recibidos',
  'orders.subtitleFor': 'Mostrando pedidos para ID de {role}: {id}',
  'orders.role.buyer': 'comprador',
  'orders.role.seller': 'vendedor',
  'orders.setupPrompt': 'Configura tu perfil en Ajustes para filtrar a tus propios pedidos',
  'orders.newOrder': '+ Nuevo Pedido',
  'orders.filter.all': 'Todos',
  'orders.filter.oneOff': 'Únicos',
  'orders.filter.recurring': 'Recurrentes',
  'orders.col.note': 'Nota',
  'orders.loadError': 'No se pudieron cargar los pedidos',
  'orders.status.pending': 'Pendiente',
  'orders.status.shipped': 'Enviado',
  'orders.status.delivered': 'Entregado',

  'analytics.title': 'Analítica',
  'analytics.subtitle.buyer': 'Resumen de tu actividad de compras',
  'analytics.subtitle.seller': 'Resumen de pedidos recibidos',
  'analytics.loading': 'Cargando analítica…',
  'analytics.empty': 'Aún no hay pedidos — la analítica aparecerá aquí una vez que tengas pedidos.',
  'analytics.stat.totalOrders': 'Pedidos Totales',
  'analytics.stat.oneOff': 'Únicos',
  'analytics.stat.recurring': 'Recurrentes',
  'analytics.stat.pending': 'Pendientes',
  'analytics.stat.shipped': 'Enviados',
  'analytics.stat.delivered': 'Entregados',
  'analytics.byStatus': 'Pedidos por Estado',
  'analytics.byCurrency': 'Pedidos por Moneda',
  'analytics.recurringFrequency': 'Frecuencia Recurrente',
  'analytics.recurringOfTotal': '{n} de {total} pedidos son recurrentes',
  'analytics.ordersPerMonth': 'Pedidos por Mes',
  'analytics.recentOrders': 'Pedidos Recientes',
  'analytics.col.date': 'Fecha',
  'analytics.freq.DAILY': 'Diaria',
  'analytics.freq.WEEKLY': 'Semanal',
  'analytics.freq.MONTHLY': 'Mensual',

  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.logout': 'Cerrar Sesión',
};

const FR: TranslationDict = {
  'brand.name': 'Northbound',
  'nav.dashboard': 'Tableau de bord',
  'nav.myOrders': 'Mes Commandes',
  'nav.orders': 'Commandes',
  'nav.receivedOrders': 'Commandes Reçues',
  'nav.templates': 'Modèles',
  'nav.analytics': 'Analytique',
  'nav.settings': 'Paramètres',
  'nav.buyerAccount': 'Compte acheteur',
  'nav.sellerAccount': 'Compte vendeur',

  'dashboard.title': 'Tableau de bord',
  'dashboard.subtitle.buyer': 'Gestion des bons de commande pour votre entreprise',
  'dashboard.subtitle.seller': 'Aperçu vendeur — suivez les commandes de vos acheteurs',
  'dashboard.totalOrders': 'Total des Commandes',
  'dashboard.ordersReceived': 'Commandes Reçues',
  'dashboard.totalSpend': 'Dépense Totale',
  'dashboard.totalRevenue': 'Revenu Total',
  'dashboard.pendingOrders': 'Commandes en Attente',
  'dashboard.ordersShipped': 'Commandes Expédiées',
  'dashboard.recurringTemplates': 'Modèles Récurrents',
  'dashboard.recentOrders': 'Commandes Récentes',
  'dashboard.recentReceivedOrders': 'Commandes Reçues Récentes',
  'dashboard.quickActions': 'Actions Rapides',
  'dashboard.createOrder': 'Créer une Commande',
  'dashboard.newTemplate': 'Nouveau Modèle',
  'dashboard.viewAllReceived': 'Voir Toutes les Commandes Reçues',
  'dashboard.completeProfilePrompt': 'Complétez votre profil pour débloquer les fonctionnalités acheteur/vendeur.',
  'dashboard.setUpProfile': 'Configurer le profil',
  'dashboard.col.orderId': 'ID Commande',
  'dashboard.col.currency': 'Devise',
  'dashboard.col.issueDate': 'Date d\'Émission',
  'dashboard.col.type': 'Type',
  'dashboard.col.status': 'Statut',
  'dashboard.loadingOrders': 'Chargement des commandes…',
  'dashboard.noOrders': 'Aucune commande trouvée.',
  'dashboard.type.recurring': 'Récurrent',
  'dashboard.type.oneOff': 'Ponctuel',
  'dashboard.couldNotLoad': 'Impossible de charger les commandes',

  'settings.title': 'Paramètres',
  'settings.subtitle': 'Préférences du compte et de la plateforme',
  'settings.account': 'Compte',
  'settings.userId': 'ID Utilisateur',
  'settings.email': 'E-mail',
  'settings.session': 'Session',
  'settings.sessionActive': 'Active',
  'settings.partyIdentity': 'Identité de la Partie',
  'settings.partyIdentityDesc': 'Votre ID de partie est automatiquement défini sur votre adresse e-mail et ne peut pas être modifié.',
  'settings.partyIdentityDescSellerSuffix': 'Partagez-le avec les acheteurs pour qu\'ils puissent vous référencer lors des commandes.',
  'settings.partyIdLabel': 'ID de Partie (external_id)',
  'settings.roleLabel': 'Rôle',
  'settings.role': 'Rôle',
  'settings.roleDesc': 'Votre rôle détermine ce que vous pouvez faire dans Northbound. Les acheteurs créent les commandes ; les vendeurs les reçoivent et les traitent.',
  'settings.role.buyer': 'Acheteur',
  'settings.role.seller': 'Vendeur',
  'settings.saveRole': 'Enregistrer le Rôle',
  'settings.saved': 'Enregistré !',
  'settings.preferences': 'Préférences',
  'settings.preferencesDesc': 'Ces préférences sont enregistrées localement et utilisées pour pré-remplir les formulaires de l\'application.',
  'settings.defaultCurrency': 'Devise par défaut',
  'settings.savedInstantly': 'Enregistré instantanément — pas besoin de cliquer sur Enregistrer.',
  'settings.platform': 'Plateforme',
  'settings.platform.application': 'Application',
  'settings.platform.purpose': 'Objectif',
  'settings.platform.purposeValue': 'Gestion des bons de commande pour petites et moyennes entreprises',
  'settings.platform.docStandard': 'Standard de Document',
  'settings.platform.backendUrl': 'URL du Backend',
  'settings.language': 'Langue',
  'settings.buyerProfile': 'Profil Acheteur',
  'settings.buyerProfileDesc': 'Enregistré localement et utilisé pour pré-remplir la section acheteur lors de la création d\'une commande ou d\'un modèle.',

  'profile.orgName': 'Nom de l\'Organisation',
  'profile.contactEmail': 'E-mail de Contact',
  'profile.street': 'Rue',
  'profile.city': 'Ville',
  'profile.country': 'Pays',
  'profile.postalCode': 'Code Postal',
  'profile.orgNamePlaceholder': 'ex. Acme Pty Ltd',
  'profile.contactEmailPlaceholder': 'contact@exemple.com',
  'profile.countryPlaceholder': 'ex. AU',

  'templates.title': 'Modèles Récurrents',
  'templates.subtitle': 'Gérer les bons de commande récurrents',
  'templates.newTemplate': '+ Nouveau Modèle',
  'templates.loading': 'Chargement des modèles…',
  'templates.empty': 'Aucun modèle récurrent pour le moment.',
  'templates.loadError': 'Impossible de charger les modèles',
  'templates.col.name': 'Nom',
  'templates.col.currency': 'Devise',
  'templates.col.frequency': 'Fréquence',
  'templates.col.interval': 'Intervalle',
  'templates.col.startDate': 'Date de Début',
  'templates.col.endDate': 'Date de Fin',
  'templates.col.actions': 'Actions',
  'templates.edit': 'Modifier',
  'templates.delete': 'Supprimer',
  'templates.ongoing': 'En cours',
  'templates.deleteConfirm': 'Supprimer ce modèle ?',
  'templates.deleteBodyPrefix': 'Le modèle',
  'templates.deleteBodySuffix': 'sera définitivement supprimé. Cette action est irréversible.',
  'templates.deleting': 'Suppression…',

  'createTemplate.backToTemplates': '← Retour aux Modèles',
  'createTemplate.title': 'Nouveau Modèle Récurrent',
  'createTemplate.templateName': 'Nom du Modèle',
  'createTemplate.nameLabel': 'Nom',
  'createTemplate.namePlaceholder': 'ex. Fournitures de bureau mensuelles',
  'createTemplate.nameHelp': 'Utilisé pour identifier ce modèle dans les listes et les menus déroulants.',
  'createTemplate.nameHelpEdit': 'Utilisé pour identifier ce modèle dans les listes et les menus déroulants. Laissez vide pour utiliser un ID abrégé.',
  'editTemplate.title': 'Modifier le Modèle',
  'editTemplate.loading': 'Chargement du modèle…',
  'editTemplate.notFound': 'Modèle introuvable.',
  'editTemplate.saving': 'Enregistrement…',
  'editTemplate.saveChanges': 'Enregistrer les Modifications',
  'createTemplate.submit': 'Créer le Modèle',
  'createTemplate.submitting': 'Création…',
  'createTemplate.recurrenceSettings': 'Paramètres de Récurrence',
  'createTemplate.frequency': 'Fréquence',
  'createTemplate.interval': 'Intervalle',
  'createTemplate.startDate': 'Date de Début',
  'createTemplate.endDate': 'Date de Fin',
  'createTemplate.endDateOptional': '(optionnel)',
  'createTemplate.currency': 'Devise',
  'createTemplate.note': 'Note',
  'createTemplate.notePlaceholder': 'Note optionnelle',
  'createTemplate.orderLines': 'Lignes de Commande',
  'createTemplate.addLine': '+ Ajouter une Ligne',
  'createTemplate.buyerSection': 'Acheteur (Votre Organisation)',
  'createTemplate.sellerSection': 'Vendeur (Fournisseur)',

  'savedSeller.heading': 'Charger un Fournisseur Enregistré',
  'savedSeller.label': 'Fournisseurs Enregistrés',
  'savedSeller.selectPlaceholder': '— Sélectionnez un fournisseur enregistré —',
  'savedSeller.forget': 'Oublier',
  'savedSeller.forgetTitle': 'Oublier ce fournisseur',
  'savedSeller.help': 'Sélectionner un fournisseur pré-remplit les champs vendeur ci-dessous. Vous pouvez toujours les modifier.',

  'orders.title.buyer': 'Mes Commandes',
  'orders.title.seller': 'Commandes Reçues',
  'orders.subtitleFor': 'Affichage des commandes pour l\'ID {role} : {id}',
  'orders.role.buyer': 'acheteur',
  'orders.role.seller': 'vendeur',
  'orders.setupPrompt': 'Configurez votre profil dans Paramètres pour filtrer vos propres commandes',
  'orders.newOrder': '+ Nouvelle Commande',
  'orders.filter.all': 'Toutes',
  'orders.filter.oneOff': 'Ponctuelles',
  'orders.filter.recurring': 'Récurrentes',
  'orders.col.note': 'Note',
  'orders.loadError': 'Impossible de charger les commandes',
  'orders.status.pending': 'En attente',
  'orders.status.shipped': 'Expédiée',
  'orders.status.delivered': 'Livrée',

  'analytics.title': 'Analytique',
  'analytics.subtitle.buyer': 'Résumé de votre activité d\'achat',
  'analytics.subtitle.seller': 'Résumé des commandes reçues',
  'analytics.loading': 'Chargement de l\'analytique…',
  'analytics.empty': 'Aucune commande pour le moment — l\'analytique apparaîtra ici une fois que vous aurez des commandes.',
  'analytics.stat.totalOrders': 'Total des Commandes',
  'analytics.stat.oneOff': 'Ponctuelles',
  'analytics.stat.recurring': 'Récurrentes',
  'analytics.stat.pending': 'En attente',
  'analytics.stat.shipped': 'Expédiées',
  'analytics.stat.delivered': 'Livrées',
  'analytics.byStatus': 'Commandes par Statut',
  'analytics.byCurrency': 'Commandes par Devise',
  'analytics.recurringFrequency': 'Fréquence Récurrente',
  'analytics.recurringOfTotal': '{n} sur {total} commandes sont récurrentes',
  'analytics.ordersPerMonth': 'Commandes par Mois',
  'analytics.recentOrders': 'Commandes Récentes',
  'analytics.col.date': 'Date',
  'analytics.freq.DAILY': 'Quotidien',
  'analytics.freq.WEEKLY': 'Hebdomadaire',
  'analytics.freq.MONTHLY': 'Mensuel',

  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.logout': 'Déconnexion',
};

const DE: TranslationDict = {
  'brand.name': 'Northbound',
  'nav.dashboard': 'Übersicht',
  'nav.myOrders': 'Meine Bestellungen',
  'nav.orders': 'Bestellungen',
  'nav.receivedOrders': 'Eingegangene Bestellungen',
  'nav.templates': 'Vorlagen',
  'nav.analytics': 'Analyse',
  'nav.settings': 'Einstellungen',
  'nav.buyerAccount': 'Käuferkonto',
  'nav.sellerAccount': 'Verkäuferkonto',

  'dashboard.title': 'Übersicht',
  'dashboard.subtitle.buyer': 'Bestellverwaltung für Ihr Unternehmen',
  'dashboard.subtitle.seller': 'Verkäuferübersicht — verfolgen Sie eingehende Bestellungen',
  'dashboard.totalOrders': 'Bestellungen gesamt',
  'dashboard.ordersReceived': 'Erhaltene Bestellungen',
  'dashboard.totalSpend': 'Gesamtausgaben',
  'dashboard.totalRevenue': 'Gesamtumsatz',
  'dashboard.pendingOrders': 'Offene Bestellungen',
  'dashboard.ordersShipped': 'Versendete Bestellungen',
  'dashboard.recurringTemplates': 'Wiederkehrende Vorlagen',
  'dashboard.recentOrders': 'Letzte Bestellungen',
  'dashboard.recentReceivedOrders': 'Letzte eingegangene Bestellungen',
  'dashboard.quickActions': 'Schnellaktionen',
  'dashboard.createOrder': 'Bestellung erstellen',
  'dashboard.newTemplate': 'Neue Vorlage',
  'dashboard.viewAllReceived': 'Alle erhaltenen Bestellungen anzeigen',
  'dashboard.completeProfilePrompt': 'Vervollständigen Sie Ihr Profil, um Käufer-/Verkäuferfunktionen freizuschalten.',
  'dashboard.setUpProfile': 'Profil einrichten',
  'dashboard.col.orderId': 'Bestell-ID',
  'dashboard.col.currency': 'Währung',
  'dashboard.col.issueDate': 'Ausstellungsdatum',
  'dashboard.col.type': 'Typ',
  'dashboard.col.status': 'Status',
  'dashboard.loadingOrders': 'Bestellungen werden geladen…',
  'dashboard.noOrders': 'Keine Bestellungen gefunden.',
  'dashboard.type.recurring': 'Wiederkehrend',
  'dashboard.type.oneOff': 'Einmalig',
  'dashboard.couldNotLoad': 'Bestellungen konnten nicht geladen werden',

  'settings.title': 'Einstellungen',
  'settings.subtitle': 'Konto- und Plattformeinstellungen',
  'settings.account': 'Konto',
  'settings.userId': 'Benutzer-ID',
  'settings.email': 'E-Mail',
  'settings.session': 'Sitzung',
  'settings.sessionActive': 'Aktiv',
  'settings.partyIdentity': 'Parteiidentität',
  'settings.partyIdentityDesc': 'Ihre Partei-ID wird automatisch auf Ihre E-Mail-Adresse gesetzt und kann nicht geändert werden.',
  'settings.partyIdentityDescSellerSuffix': 'Teilen Sie sie mit Käufern, damit diese Sie bei Bestellungen referenzieren können.',
  'settings.partyIdLabel': 'Partei-ID (external_id)',
  'settings.roleLabel': 'Rolle',
  'settings.role': 'Rolle',
  'settings.roleDesc': 'Ihre Rolle bestimmt, was Sie in Northbound tun können. Käufer erstellen Bestellungen; Verkäufer empfangen und erfüllen sie.',
  'settings.role.buyer': 'Käufer',
  'settings.role.seller': 'Verkäufer',
  'settings.saveRole': 'Rolle speichern',
  'settings.saved': 'Gespeichert!',
  'settings.preferences': 'Einstellungen',
  'settings.preferencesDesc': 'Diese Einstellungen werden lokal gespeichert und zum Vorausfüllen von Formularen in der App verwendet.',
  'settings.defaultCurrency': 'Standardwährung',
  'settings.savedInstantly': 'Sofort gespeichert — kein Klick auf Speichern erforderlich.',
  'settings.platform': 'Plattform',
  'settings.platform.application': 'Anwendung',
  'settings.platform.purpose': 'Zweck',
  'settings.platform.purposeValue': 'Bestellverwaltung für kleine und mittlere Unternehmen',
  'settings.platform.docStandard': 'Dokumentstandard',
  'settings.platform.backendUrl': 'Backend-URL',
  'settings.language': 'Sprache',
  'settings.buyerProfile': 'Käuferprofil',
  'settings.buyerProfileDesc': 'Lokal gespeichert und zum Vorausfüllen des Käuferabschnitts beim Erstellen einer Bestellung oder Vorlage verwendet.',

  'profile.orgName': 'Organisationsname',
  'profile.contactEmail': 'Kontakt-E-Mail',
  'profile.street': 'Straße',
  'profile.city': 'Stadt',
  'profile.country': 'Land',
  'profile.postalCode': 'Postleitzahl',
  'profile.orgNamePlaceholder': 'z. B. Acme Pty Ltd',
  'profile.contactEmailPlaceholder': 'kontakt@beispiel.com',
  'profile.countryPlaceholder': 'z. B. AU',

  'templates.title': 'Wiederkehrende Vorlagen',
  'templates.subtitle': 'Wiederkehrende Bestellungen verwalten',
  'templates.newTemplate': '+ Neue Vorlage',
  'templates.loading': 'Vorlagen werden geladen…',
  'templates.empty': 'Noch keine wiederkehrenden Vorlagen.',
  'templates.loadError': 'Vorlagen konnten nicht geladen werden',
  'templates.col.name': 'Name',
  'templates.col.currency': 'Währung',
  'templates.col.frequency': 'Frequenz',
  'templates.col.interval': 'Intervall',
  'templates.col.startDate': 'Startdatum',
  'templates.col.endDate': 'Enddatum',
  'templates.col.actions': 'Aktionen',
  'templates.edit': 'Bearbeiten',
  'templates.delete': 'Löschen',
  'templates.ongoing': 'Laufend',
  'templates.deleteConfirm': 'Diese Vorlage löschen?',
  'templates.deleteBodyPrefix': 'Vorlage',
  'templates.deleteBodySuffix': 'wird dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden.',
  'templates.deleting': 'Wird gelöscht…',

  'createTemplate.backToTemplates': '← Zurück zu Vorlagen',
  'createTemplate.title': 'Neue wiederkehrende Vorlage',
  'createTemplate.templateName': 'Vorlagenname',
  'createTemplate.nameLabel': 'Name',
  'createTemplate.namePlaceholder': 'z. B. Monatlicher Bürobedarf',
  'createTemplate.nameHelp': 'Wird verwendet, um diese Vorlage in Listen und Dropdowns zu identifizieren.',
  'createTemplate.nameHelpEdit': 'Wird verwendet, um diese Vorlage in Listen und Dropdowns zu identifizieren. Leer lassen, um eine verkürzte ID zu verwenden.',
  'editTemplate.title': 'Vorlage bearbeiten',
  'editTemplate.loading': 'Vorlage wird geladen…',
  'editTemplate.notFound': 'Vorlage nicht gefunden.',
  'editTemplate.saving': 'Wird gespeichert…',
  'editTemplate.saveChanges': 'Änderungen speichern',
  'createTemplate.submit': 'Vorlage erstellen',
  'createTemplate.submitting': 'Wird erstellt…',
  'createTemplate.recurrenceSettings': 'Wiederholungseinstellungen',
  'createTemplate.frequency': 'Frequenz',
  'createTemplate.interval': 'Intervall',
  'createTemplate.startDate': 'Startdatum',
  'createTemplate.endDate': 'Enddatum',
  'createTemplate.endDateOptional': '(optional)',
  'createTemplate.currency': 'Währung',
  'createTemplate.note': 'Notiz',
  'createTemplate.notePlaceholder': 'Optionale Notiz',
  'createTemplate.orderLines': 'Bestellpositionen',
  'createTemplate.addLine': '+ Position hinzufügen',
  'createTemplate.buyerSection': 'Käufer (Ihre Organisation)',
  'createTemplate.sellerSection': 'Verkäufer (Lieferant)',

  'savedSeller.heading': 'Gespeicherten Lieferanten laden',
  'savedSeller.label': 'Gespeicherte Lieferanten',
  'savedSeller.selectPlaceholder': '— Gespeicherten Lieferanten auswählen —',
  'savedSeller.forget': 'Entfernen',
  'savedSeller.forgetTitle': 'Diesen Lieferanten vergessen',
  'savedSeller.help': 'Die Auswahl eines Lieferanten füllt die Verkäuferfelder unten aus. Sie können sie weiterhin bearbeiten.',

  'orders.title.buyer': 'Meine Bestellungen',
  'orders.title.seller': 'Eingegangene Bestellungen',
  'orders.subtitleFor': 'Bestellungen für {role}-ID: {id}',
  'orders.role.buyer': 'Käufer',
  'orders.role.seller': 'Verkäufer',
  'orders.setupPrompt': 'Richten Sie Ihr Profil in Einstellungen ein, um nach Ihren eigenen Bestellungen zu filtern',
  'orders.newOrder': '+ Neue Bestellung',
  'orders.filter.all': 'Alle',
  'orders.filter.oneOff': 'Einmalig',
  'orders.filter.recurring': 'Wiederkehrend',
  'orders.col.note': 'Notiz',
  'orders.loadError': 'Bestellungen konnten nicht geladen werden',
  'orders.status.pending': 'Ausstehend',
  'orders.status.shipped': 'Versendet',
  'orders.status.delivered': 'Geliefert',

  'analytics.title': 'Analyse',
  'analytics.subtitle.buyer': 'Zusammenfassung Ihrer Einkaufsaktivitäten',
  'analytics.subtitle.seller': 'Zusammenfassung der eingegangenen Bestellungen',
  'analytics.loading': 'Analyse wird geladen…',
  'analytics.empty': 'Noch keine Bestellungen — die Analyse erscheint hier, sobald Sie Bestellungen haben.',
  'analytics.stat.totalOrders': 'Bestellungen gesamt',
  'analytics.stat.oneOff': 'Einmalig',
  'analytics.stat.recurring': 'Wiederkehrend',
  'analytics.stat.pending': 'Ausstehend',
  'analytics.stat.shipped': 'Versendet',
  'analytics.stat.delivered': 'Geliefert',
  'analytics.byStatus': 'Bestellungen nach Status',
  'analytics.byCurrency': 'Bestellungen nach Währung',
  'analytics.recurringFrequency': 'Wiederkehrende Frequenz',
  'analytics.recurringOfTotal': '{n} von {total} Bestellungen sind wiederkehrend',
  'analytics.ordersPerMonth': 'Bestellungen pro Monat',
  'analytics.recentOrders': 'Letzte Bestellungen',
  'analytics.col.date': 'Datum',
  'analytics.freq.DAILY': 'Täglich',
  'analytics.freq.WEEKLY': 'Wöchentlich',
  'analytics.freq.MONTHLY': 'Monatlich',

  'common.cancel': 'Abbrechen',
  'common.save': 'Speichern',
  'common.logout': 'Abmelden',
};

const ZH: TranslationDict = {
  'brand.name': 'Northbound',
  'nav.dashboard': '仪表板',
  'nav.myOrders': '我的订单',
  'nav.orders': '订单',
  'nav.receivedOrders': '收到的订单',
  'nav.templates': '模板',
  'nav.analytics': '分析',
  'nav.settings': '设置',
  'nav.buyerAccount': '买家账户',
  'nav.sellerAccount': '卖家账户',

  'dashboard.title': '仪表板',
  'dashboard.subtitle.buyer': '为您的企业管理采购订单',
  'dashboard.subtitle.seller': '卖家概览 — 跟踪来自买家的订单',
  'dashboard.totalOrders': '订单总数',
  'dashboard.ordersReceived': '收到的订单',
  'dashboard.totalSpend': '总支出',
  'dashboard.totalRevenue': '总收入',
  'dashboard.pendingOrders': '待处理订单',
  'dashboard.ordersShipped': '已发货订单',
  'dashboard.recurringTemplates': '周期性模板',
  'dashboard.recentOrders': '最近订单',
  'dashboard.recentReceivedOrders': '最近收到的订单',
  'dashboard.quickActions': '快捷操作',
  'dashboard.createOrder': '创建订单',
  'dashboard.newTemplate': '新建模板',
  'dashboard.viewAllReceived': '查看全部收到的订单',
  'dashboard.completeProfilePrompt': '完善您的个人资料以解锁买家/卖家功能。',
  'dashboard.setUpProfile': '设置资料',
  'dashboard.col.orderId': '订单ID',
  'dashboard.col.currency': '货币',
  'dashboard.col.issueDate': '签发日期',
  'dashboard.col.type': '类型',
  'dashboard.col.status': '状态',
  'dashboard.loadingOrders': '正在加载订单…',
  'dashboard.noOrders': '未找到订单。',
  'dashboard.type.recurring': '周期',
  'dashboard.type.oneOff': '一次性',
  'dashboard.couldNotLoad': '无法加载订单',

  'settings.title': '设置',
  'settings.subtitle': '账户和平台偏好',
  'settings.account': '账户',
  'settings.userId': '用户ID',
  'settings.email': '电子邮件',
  'settings.session': '会话',
  'settings.sessionActive': '活跃',
  'settings.partyIdentity': '身份信息',
  'settings.partyIdentityDesc': '您的身份ID会自动设置为您的电子邮件地址,无法更改。',
  'settings.partyIdentityDescSellerSuffix': '与买家分享此ID,以便他们在下订单时引用您。',
  'settings.partyIdLabel': '身份ID (external_id)',
  'settings.roleLabel': '角色',
  'settings.role': '角色',
  'settings.roleDesc': '您的角色决定您在Northbound中可以做什么。买家创建订单;卖家接收并履行订单。',
  'settings.role.buyer': '买家',
  'settings.role.seller': '卖家',
  'settings.saveRole': '保存角色',
  'settings.saved': '已保存!',
  'settings.preferences': '偏好',
  'settings.preferencesDesc': '这些偏好保存在本地,用于在整个应用中预填表单。',
  'settings.defaultCurrency': '默认货币',
  'settings.savedInstantly': '即时保存 — 无需点击保存。',
  'settings.platform': '平台',
  'settings.platform.application': '应用程序',
  'settings.platform.purpose': '用途',
  'settings.platform.purposeValue': '面向中小企业的采购订单管理',
  'settings.platform.docStandard': '文档标准',
  'settings.platform.backendUrl': '后端URL',
  'settings.language': '语言',
  'settings.buyerProfile': '买家资料',
  'settings.buyerProfileDesc': '保存在本地,用于在创建订单或模板时预填买家部分。',

  'profile.orgName': '组织名称',
  'profile.contactEmail': '联系邮箱',
  'profile.street': '街道',
  'profile.city': '城市',
  'profile.country': '国家',
  'profile.postalCode': '邮政编码',
  'profile.orgNamePlaceholder': '例如 Acme Pty Ltd',
  'profile.contactEmailPlaceholder': 'contact@example.com',
  'profile.countryPlaceholder': '例如 AU',

  'templates.title': '周期性模板',
  'templates.subtitle': '管理重复采购订单',
  'templates.newTemplate': '+ 新建模板',
  'templates.loading': '正在加载模板…',
  'templates.empty': '暂无周期性模板。',
  'templates.loadError': '无法加载模板',
  'templates.col.name': '名称',
  'templates.col.currency': '货币',
  'templates.col.frequency': '频率',
  'templates.col.interval': '间隔',
  'templates.col.startDate': '开始日期',
  'templates.col.endDate': '结束日期',
  'templates.col.actions': '操作',
  'templates.edit': '编辑',
  'templates.delete': '删除',
  'templates.ongoing': '进行中',
  'templates.deleteConfirm': '删除此模板?',
  'templates.deleteBodyPrefix': '模板',
  'templates.deleteBodySuffix': '将被永久删除。此操作无法撤销。',
  'templates.deleting': '正在删除…',

  'createTemplate.backToTemplates': '← 返回模板',
  'createTemplate.title': '新建周期性模板',
  'createTemplate.templateName': '模板名称',
  'createTemplate.nameLabel': '名称',
  'createTemplate.namePlaceholder': '例如 每月办公用品',
  'createTemplate.nameHelp': '用于在列表和下拉菜单中标识此模板。',
  'createTemplate.nameHelpEdit': '用于在列表和下拉菜单中标识此模板。留空则使用缩短的ID。',
  'editTemplate.title': '编辑模板',
  'editTemplate.loading': '正在加载模板…',
  'editTemplate.notFound': '未找到模板。',
  'editTemplate.saving': '正在保存…',
  'editTemplate.saveChanges': '保存更改',
  'createTemplate.submit': '创建模板',
  'createTemplate.submitting': '正在创建…',
  'createTemplate.recurrenceSettings': '周期设置',
  'createTemplate.frequency': '频率',
  'createTemplate.interval': '间隔',
  'createTemplate.startDate': '开始日期',
  'createTemplate.endDate': '结束日期',
  'createTemplate.endDateOptional': '(可选)',
  'createTemplate.currency': '货币',
  'createTemplate.note': '备注',
  'createTemplate.notePlaceholder': '可选备注',
  'createTemplate.orderLines': '订单明细',
  'createTemplate.addLine': '+ 添加明细',
  'createTemplate.buyerSection': '买家(您的组织)',
  'createTemplate.sellerSection': '卖家(供应商)',

  'savedSeller.heading': '加载已保存的供应商',
  'savedSeller.label': '已保存的供应商',
  'savedSeller.selectPlaceholder': '— 选择已保存的供应商 —',
  'savedSeller.forget': '忘记',
  'savedSeller.forgetTitle': '忘记此供应商',
  'savedSeller.help': '选择供应商会预填下方的卖家字段。您仍然可以编辑它们。',

  'orders.title.buyer': '我的订单',
  'orders.title.seller': '收到的订单',
  'orders.subtitleFor': '显示{role}ID的订单: {id}',
  'orders.role.buyer': '买家',
  'orders.role.seller': '卖家',
  'orders.setupPrompt': '在设置中完善您的个人资料,以筛选您自己的订单',
  'orders.newOrder': '+ 新建订单',
  'orders.filter.all': '全部',
  'orders.filter.oneOff': '一次性',
  'orders.filter.recurring': '周期性',
  'orders.col.note': '备注',
  'orders.loadError': '无法加载订单',
  'orders.status.pending': '待处理',
  'orders.status.shipped': '已发货',
  'orders.status.delivered': '已送达',

  'analytics.title': '分析',
  'analytics.subtitle.buyer': '您的采购活动摘要',
  'analytics.subtitle.seller': '收到的订单摘要',
  'analytics.loading': '正在加载分析…',
  'analytics.empty': '暂无订单 — 有订单后,分析将显示在此处。',
  'analytics.stat.totalOrders': '订单总数',
  'analytics.stat.oneOff': '一次性',
  'analytics.stat.recurring': '周期性',
  'analytics.stat.pending': '待处理',
  'analytics.stat.shipped': '已发货',
  'analytics.stat.delivered': '已送达',
  'analytics.byStatus': '按状态分类的订单',
  'analytics.byCurrency': '按货币分类的订单',
  'analytics.recurringFrequency': '周期频率',
  'analytics.recurringOfTotal': '{total}个订单中有{n}个是周期性的',
  'analytics.ordersPerMonth': '每月订单数',
  'analytics.recentOrders': '最近订单',
  'analytics.col.date': '日期',
  'analytics.freq.DAILY': '每日',
  'analytics.freq.WEEKLY': '每周',
  'analytics.freq.MONTHLY': '每月',

  'common.cancel': '取消',
  'common.save': '保存',
  'common.logout': '退出登录',
};

const DICTIONARIES: Record<LanguageCode, TranslationDict> = {
  en: EN,
  es: ES,
  fr: FR,
  de: DE,
  zh: ZH,
};

const STORAGE_KEY = 'northbound_language';

interface LanguageContextValue {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function loadLanguage(): LanguageCode {
  try {
    const stored = localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
    if (stored && DICTIONARIES[stored]) return stored;
  } catch {
    // localStorage unavailable
  }
  return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(loadLanguage);

  const setLanguage = useCallback((code: LanguageCode) => {
    setLanguageState(code);
    try {
      localStorage.setItem(STORAGE_KEY, code);
    } catch {
      // silently fail
    }
  }, []);

  // Reflect the active language on <html lang="..."> for accessibility
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback(
    (key: string): string => {
      const dict = DICTIONARIES[language] ?? EN;
      return dict[key] ?? EN[key] ?? key;
    },
    [language],
  );

  const value = useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}
